### ISSUE TITLE
Get raw images as numpy arrays from python interface

### ISSUE THREAD

**Issue by PWhiddy** [DiracInstitute/kbmod#40]

**Comment by jbkalmbach** [comment]
Let's also add set array option.

**Comment by PWhiddy** [comment]
https://github.com/DiracInstitute/kbmod/commit/437c4d17443f15385b51e09a68bddcdc8c7d3843
https://github.com/DiracInstitute/kbmod/commit/5e74a4783a20181acd7c1f5d66b7c76cc77079c3
https://github.com/DiracInstitute/kbmod/commit/506d3479498da9c56370915b421dcdffc85f289
https://github.com/DiracInstitute/kbmod/commit/5ee6aea9c14aa2b7bb7b7e88ff4809907fc46cc97
